#ifndef mk_win_base_user_functions
#define mk_win_base_user_functions


#include "mk_win_base_keywords.h"
#include "mk_win_base_types.h"
#include "mk_win_base_user_types.h"

#include "../../mk_utils/src/mk_cpp.h"


mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_atom_t mk_win_base_keywords_calling_convention_api RegisterClass(mk_win_base_user_types_class_a_lpt);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_atom_t mk_win_base_keywords_calling_convention_api RegisterClassA(mk_win_base_user_types_class_a_lpt);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_atom_t mk_win_base_keywords_calling_convention_api RegisterClassB(mk_win_base_user_types_class_w_lpt);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_atom_t mk_win_base_keywords_calling_convention_api RegisterClassExA(mk_win_base_user_types_class_exa_lpt);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_atom_t mk_win_base_keywords_calling_convention_api RegisterClassExW(mk_win_base_user_types_class_exw_lpt);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hwnd_t mk_win_base_keywords_calling_convention_api CreateWindow(mk_win_base_types_strac_t, mk_win_base_types_strac_t, mk_win_base_types_dword_t, int, int, int, int, mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hmenu_t, mk_win_base_types_hinstance_t, mk_win_base_types_void_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hwnd_t mk_win_base_keywords_calling_convention_api CreateWindowA(mk_win_base_types_strac_t, mk_win_base_types_strac_t, mk_win_base_types_dword_t, int, int, int, int, mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hmenu_t, mk_win_base_types_hinstance_t, mk_win_base_types_void_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hwnd_t mk_win_base_keywords_calling_convention_api CreateWindowW(mk_win_base_types_strwc_t, mk_win_base_types_strwc_t, mk_win_base_types_dword_t, int, int, int, int, mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hmenu_t, mk_win_base_types_hinstance_t, mk_win_base_types_void_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hwnd_t mk_win_base_keywords_calling_convention_api CreateWindowEx(mk_win_base_types_dword_t, mk_win_base_types_strac_t, mk_win_base_types_strac_t, mk_win_base_types_dword_t, int, int, int, int, mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hmenu_t, mk_win_base_types_hinstance_t, mk_win_base_types_void_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hwnd_t mk_win_base_keywords_calling_convention_api CreateWindowExA(mk_win_base_types_dword_t, mk_win_base_types_strac_t, mk_win_base_types_strac_t, mk_win_base_types_dword_t, int, int, int, int, mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hmenu_t, mk_win_base_types_hinstance_t, mk_win_base_types_void_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hwnd_t mk_win_base_keywords_calling_convention_api CreateWindowExW(mk_win_base_types_dword_t, mk_win_base_types_strwc_t, mk_win_base_types_strwc_t, mk_win_base_types_dword_t, int, int, int, int, mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hmenu_t, mk_win_base_types_hinstance_t, mk_win_base_types_void_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DefWindowProc(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DefWindowProcA(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DefWindowProcW(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api GetMessage(mk_win_base_user_types_msg_lpt, mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_types_uint_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api GetMessageA(mk_win_base_user_types_msg_lpt, mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_types_uint_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api GetMessageW(mk_win_base_user_types_msg_lpt, mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_types_uint_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api TranslateMessage(mk_win_base_user_types_msg_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DispatchMessage(mk_win_base_user_types_msg_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DispatchMessageA(mk_win_base_user_types_msg_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DispatchMessageW(mk_win_base_user_types_msg_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api ShowWindow(mk_win_base_user_types_hwnd_t, int);


#endif
