#ifndef mk_include_guard_win_base_kernel_functions
#define mk_include_guard_win_base_kernel_functions


#include "mk_win_base_kernel_types.h"
#include "mk_win_base_keywords.h"
#include "mk_win_base_types.h"

#include "../../mk_utils/src/mk_cpp.h"


mk_extern_c mk_win_base_keywords_dll_import mk_win_base_kernel_types_hmodule_t mk_win_base_keywords_calling_convention_api GetModuleHandle(mk_win_base_types_char_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_kernel_types_hmodule_t mk_win_base_keywords_calling_convention_api GetModuleHandleA(mk_win_base_types_char_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_kernel_types_hmodule_t mk_win_base_keywords_calling_convention_api GetModuleHandleW(mk_win_base_types_wchar_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_kernel_types_farproc_t mk_win_base_keywords_calling_convention_api GetProcAddress(mk_win_base_kernel_types_hmodule_t, mk_win_base_types_char_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_kernel_types_hrsrc_t mk_win_base_keywords_calling_convention_api FindResource(mk_win_base_kernel_types_hmodule_t, mk_win_base_types_char_lpct, mk_win_base_types_char_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_kernel_types_hrsrc_t mk_win_base_keywords_calling_convention_api FindResourceA(mk_win_base_kernel_types_hmodule_t, mk_win_base_types_char_lpct, mk_win_base_types_char_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_kernel_types_hglobal_t mk_win_base_keywords_calling_convention_api LoadResource(mk_win_base_kernel_types_hmodule_t, mk_win_base_kernel_types_hrsrc_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_void_lpt mk_win_base_keywords_calling_convention_api LockResource(mk_win_base_kernel_types_hglobal_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_handle_t mk_win_base_keywords_calling_convention_api CreateFileA(mk_win_base_types_char_lpct, mk_win_base_types_dword_t, mk_win_base_types_dword_t, mk_win_base_types_void_lpct, mk_win_base_types_dword_t, mk_win_base_types_dword_t, mk_win_base_types_handle_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_handle_t mk_win_base_keywords_calling_convention_api CreateFileW(mk_win_base_types_wchar_lpct, mk_win_base_types_dword_t, mk_win_base_types_dword_t, mk_win_base_types_void_lpct, mk_win_base_types_dword_t, mk_win_base_types_dword_t, mk_win_base_types_handle_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_dword_t mk_win_base_keywords_calling_convention_api GetFileSize(mk_win_base_types_handle_t, mk_win_base_types_dword_lpt);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_dword_t mk_win_base_keywords_calling_convention_api GetLastError(void);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api CloseHandle(mk_win_base_types_handle_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_handle_t mk_win_base_keywords_calling_convention_api CreateFileMappingA(mk_win_base_types_handle_t, mk_win_base_types_void_lpt, mk_win_base_types_dword_t, mk_win_base_types_dword_t, mk_win_base_types_dword_t, mk_win_base_types_char_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_handle_t mk_win_base_keywords_calling_convention_api CreateFileMappingW(mk_win_base_types_handle_t, mk_win_base_types_void_lpt, mk_win_base_types_dword_t, mk_win_base_types_dword_t, mk_win_base_types_dword_t, mk_win_base_types_wchar_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_void_lpt mk_win_base_keywords_calling_convention_api MapViewOfFile(mk_win_base_types_handle_t, mk_win_base_types_dword_t, mk_win_base_types_dword_t, mk_win_base_types_dword_t, mk_win_base_types_uintptr_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api UnmapViewOfFile(mk_win_base_types_void_lpct);


#endif
