#ifndef mk_win_base_user_functions
#define mk_win_base_user_functions


#include "mk_win_base_keywords.h"
#include "mk_win_base_types.h"
#include "mk_win_base_user_types.h"

#include "../../mk_utils/src/mk_cpp.h"


#define mk_win_base_user_functions_make_int_resource_a(x) ((mk_win_base_types_strac_t)(mk_win_base_types_uintptr_t)((x) & 0xffffu))
#define mk_win_base_user_functions_make_int_resource_w(x) ((mk_win_base_types_strwc_t)(mk_win_base_types_uintptr_t)((x) & 0xffffu))
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hicon_t mk_win_base_keywords_calling_convention_api LoadIcon(mk_win_base_types_hinstance_t, mk_win_base_types_strac_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hicon_t mk_win_base_keywords_calling_convention_api LoadIconA(mk_win_base_types_hinstance_t, mk_win_base_types_strac_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hicon_t mk_win_base_keywords_calling_convention_api LoadIconW(mk_win_base_types_hinstance_t, mk_win_base_types_strwc_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hcursor_t mk_win_base_keywords_calling_convention_api LoadCursor(mk_win_base_types_hinstance_t, mk_win_base_types_strac_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hcursor_t mk_win_base_keywords_calling_convention_api LoadCursorA(mk_win_base_types_hinstance_t, mk_win_base_types_strac_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hcursor_t mk_win_base_keywords_calling_convention_api LoadCursorW(mk_win_base_types_hinstance_t, mk_win_base_types_strwc_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_atom_t mk_win_base_keywords_calling_convention_api RegisterClass(mk_win_base_user_types_class_a_lpt);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_atom_t mk_win_base_keywords_calling_convention_api RegisterClassA(mk_win_base_user_types_class_a_lpt);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_atom_t mk_win_base_keywords_calling_convention_api RegisterClassW(mk_win_base_user_types_class_w_lpt);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_atom_t mk_win_base_keywords_calling_convention_api RegisterClassExA(mk_win_base_user_types_class_exa_lpt);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_atom_t mk_win_base_keywords_calling_convention_api RegisterClassExW(mk_win_base_user_types_class_exw_lpt);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hwnd_t mk_win_base_keywords_calling_convention_api CreateWindow(mk_win_base_types_strac_t, mk_win_base_types_strac_t, mk_win_base_types_dword_t, int, int, int, int, mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hmenu_t, mk_win_base_types_hinstance_t, mk_win_base_types_void_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hwnd_t mk_win_base_keywords_calling_convention_api CreateWindowA(mk_win_base_types_strac_t, mk_win_base_types_strac_t, mk_win_base_types_dword_t, int, int, int, int, mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hmenu_t, mk_win_base_types_hinstance_t, mk_win_base_types_void_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hwnd_t mk_win_base_keywords_calling_convention_api CreateWindowW(mk_win_base_types_strwc_t, mk_win_base_types_strwc_t, mk_win_base_types_dword_t, int, int, int, int, mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hmenu_t, mk_win_base_types_hinstance_t, mk_win_base_types_void_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hwnd_t mk_win_base_keywords_calling_convention_api CreateWindowEx(mk_win_base_types_dword_t, mk_win_base_types_strac_t, mk_win_base_types_strac_t, mk_win_base_types_dword_t, int, int, int, int, mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hmenu_t, mk_win_base_types_hinstance_t, mk_win_base_types_void_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hwnd_t mk_win_base_keywords_calling_convention_api CreateWindowExA(mk_win_base_types_dword_t, mk_win_base_types_strac_t, mk_win_base_types_strac_t, mk_win_base_types_dword_t, int, int, int, int, mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hmenu_t, mk_win_base_types_hinstance_t, mk_win_base_types_void_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hwnd_t mk_win_base_keywords_calling_convention_api CreateWindowExW(mk_win_base_types_dword_t, mk_win_base_types_strwc_t, mk_win_base_types_strwc_t, mk_win_base_types_dword_t, int, int, int, int, mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hmenu_t, mk_win_base_types_hinstance_t, mk_win_base_types_void_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_uintptr_t mk_win_base_keywords_calling_convention_api SetWindowLong(mk_win_base_user_types_hwnd_t, int, mk_win_base_types_uintptr_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_uintptr_t mk_win_base_keywords_calling_convention_api SetWindowLongA(mk_win_base_user_types_hwnd_t, int, mk_win_base_types_uintptr_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_uintptr_t mk_win_base_keywords_calling_convention_api SetWindowLongW(mk_win_base_user_types_hwnd_t, int, mk_win_base_types_uintptr_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_uintptr_t mk_win_base_keywords_calling_convention_api SetWindowLongPtrA(mk_win_base_user_types_hwnd_t, int, mk_win_base_types_uintptr_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_uintptr_t mk_win_base_keywords_calling_convention_api SetWindowLongPtrW(mk_win_base_user_types_hwnd_t, int, mk_win_base_types_uintptr_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_uintptr_t mk_win_base_keywords_calling_convention_api GetWindowLong(mk_win_base_user_types_hwnd_t, int);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_uintptr_t mk_win_base_keywords_calling_convention_api GetWindowLongA(mk_win_base_user_types_hwnd_t, int);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_uintptr_t mk_win_base_keywords_calling_convention_api GetWindowLongW(mk_win_base_user_types_hwnd_t, int);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_uintptr_t mk_win_base_keywords_calling_convention_api GetWindowLongPtrA(mk_win_base_user_types_hwnd_t, int);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_uintptr_t mk_win_base_keywords_calling_convention_api GetWindowLongPtrW(mk_win_base_user_types_hwnd_t, int);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DefWindowProc(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DefWindowProcA(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DefWindowProcW(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DefFrameProc(mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DefFrameProcA(mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DefFrameProcW(mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DefMDIChildProc(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DefMDIChildProcA(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DefMDIChildProcW(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api PostMessage(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api PostMessageA(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api PostMessageW(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api SendMessage(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api SendMessageA(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api SendMessageW(mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_user_types_wparam_t, mk_win_base_user_types_lparam_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api GetMessage(mk_win_base_user_types_msg_lpt, mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_types_uint_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api GetMessageA(mk_win_base_user_types_msg_lpt, mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_types_uint_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api GetMessageW(mk_win_base_user_types_msg_lpt, mk_win_base_user_types_hwnd_t, mk_win_base_types_uint_t, mk_win_base_types_uint_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api TranslateMessage(mk_win_base_user_types_msg_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api TranslateMDISysAccel(mk_win_base_user_types_hwnd_t, mk_win_base_user_types_msg_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DispatchMessage(mk_win_base_user_types_msg_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DispatchMessageA(mk_win_base_user_types_msg_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_lresult_t mk_win_base_keywords_calling_convention_api DispatchMessageW(mk_win_base_user_types_msg_lpct);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api IsChild(mk_win_base_user_types_hwnd_t, mk_win_base_user_types_hwnd_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_types_bool_t mk_win_base_keywords_calling_convention_api ShowWindow(mk_win_base_user_types_hwnd_t, int);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hmenu_t mk_win_base_keywords_calling_convention_api GetMenu(mk_win_base_user_types_hwnd_t);
mk_extern_c mk_win_base_keywords_dll_import mk_win_base_user_types_hmenu_t mk_win_base_keywords_calling_convention_api GetSubMenu(mk_win_base_user_types_hmenu_t, int);
mk_extern_c mk_win_base_keywords_dll_import void mk_win_base_keywords_calling_convention_api PostQuitMessage(int);


#endif
