#undef mk_num_set_zero
#undef mk_num_set_one
#undef mk_num_set_mask

#undef mk_num_from_buff_le
#undef mk_num_from_buff_be
#undef mk_num_to_buff_le
#undef mk_num_to_buff_be

#undef mk_num_from_char
#undef mk_num_from_uchar
#undef mk_num_from_schar
#undef mk_num_from_ushort
#undef mk_num_from_sshort
#undef mk_num_from_uint
#undef mk_num_from_sint
#undef mk_num_from_ulong
#undef mk_num_from_slong
#undef mk_num_from_ullong
#undef mk_num_from_sllong
#undef mk_num_from_sizet
#undef mk_num_from_umaxt
#undef mk_num_from_smaxt

#undef mk_num_to_char
#undef mk_num_to_uchar
#undef mk_num_to_schar
#undef mk_num_to_ushort
#undef mk_num_to_sshort
#undef mk_num_to_uint
#undef mk_num_to_sint
#undef mk_num_to_ulong
#undef mk_num_to_slong
#undef mk_num_to_ullong
#undef mk_num_to_sllong
#undef mk_num_to_sizet
#undef mk_num_to_umaxt
#undef mk_num_to_smaxt

#undef mk_num_is_zero
#undef mk_num_eq
#undef mk_num_ne
#undef mk_num_lt
#undef mk_num_le
#undef mk_num_gt
#undef mk_num_ge

#undef mk_num_inc
#undef mk_num_dec

#undef mk_num_not2
#undef mk_num_not1
#undef mk_num_or3
#undef mk_num_or2
#undef mk_num_and3
#undef mk_num_and2
#undef mk_num_xor3
#undef mk_num_xor2

#undef mk_num_shl3
#undef mk_num_shl2
#undef mk_num_shr3
#undef mk_num_shr2

#undef mk_num_add3_wrap_cid_cod
#undef mk_num_add3_wrap_cid_coe
#undef mk_num_add3_wrap_cie_cod
#undef mk_num_add3_wrap_cie_coe
#undef mk_num_add3_sat_cid_cod
#undef mk_num_add3_sat_cid_coe
#undef mk_num_add3_sat_cie_cod
#undef mk_num_add3_sat_cie_coe
#undef mk_num_add3_crash_cid_cod
#undef mk_num_add3_crash_cid_coe
#undef mk_num_add3_crash_cie_cod
#undef mk_num_add3_crash_cie_coe
#undef mk_num_add2_wrap_cid_cod
#undef mk_num_add2_wrap_cid_coe
#undef mk_num_add2_wrap_cie_cod
#undef mk_num_add2_wrap_cie_coe
#undef mk_num_add2_sat_cid_cod
#undef mk_num_add2_sat_cid_coe
#undef mk_num_add2_sat_cie_cod
#undef mk_num_add2_sat_cie_coe
#undef mk_num_add2_crash_cid_cod
#undef mk_num_add2_crash_cid_coe
#undef mk_num_add2_crash_cie_cod
#undef mk_num_add2_crash_cie_coe

#undef mk_num_sub3_wrap_cid_cod
#undef mk_num_sub3_wrap_cid_coe
#undef mk_num_sub3_wrap_cie_cod
#undef mk_num_sub3_wrap_cie_coe
#undef mk_num_sub3_sat_cid_cod
#undef mk_num_sub3_sat_cid_coe
#undef mk_num_sub3_sat_cie_cod
#undef mk_num_sub3_sat_cie_coe
#undef mk_num_sub3_crash_cid_cod
#undef mk_num_sub3_crash_cid_coe
#undef mk_num_sub3_crash_cie_cod
#undef mk_num_sub3_crash_cie_coe
#undef mk_num_sub2_wrap_cid_cod
#undef mk_num_sub2_wrap_cid_coe
#undef mk_num_sub2_wrap_cie_cod
#undef mk_num_sub2_wrap_cie_coe
#undef mk_num_sub2_sat_cid_cod
#undef mk_num_sub2_sat_cid_coe
#undef mk_num_sub2_sat_cie_cod
#undef mk_num_sub2_sat_cie_coe
#undef mk_num_sub2_crash_cid_cod
#undef mk_num_sub2_crash_cid_coe
#undef mk_num_sub2_crash_cie_cod
#undef mk_num_sub2_crash_cie_coe

#undef mk_num_mul3_wrap_cid_cod
#undef mk_num_mul3_wrap_cid_coe
#undef mk_num_mul3_wrap_cie_cod
#undef mk_num_mul3_wrap_cie_coe
#undef mk_num_mul3_sat_cid_cod
#undef mk_num_mul3_sat_cid_coe
#undef mk_num_mul3_sat_cie_cod
#undef mk_num_mul3_sat_cie_coe
#undef mk_num_mul3_crash_cid_cod
#undef mk_num_mul3_crash_cid_coe
#undef mk_num_mul3_crash_cie_cod
#undef mk_num_mul3_crash_cie_coe
#undef mk_num_mul2_wrap_cid_cod
#undef mk_num_mul2_wrap_cid_coe
#undef mk_num_mul2_wrap_cie_cod
#undef mk_num_mul2_wrap_cie_coe
#undef mk_num_mul2_sat_cid_cod
#undef mk_num_mul2_sat_cid_coe
#undef mk_num_mul2_sat_cie_cod
#undef mk_num_mul2_sat_cie_coe
#undef mk_num_mul2_crash_cid_cod
#undef mk_num_mul2_crash_cid_coe
#undef mk_num_mul2_crash_cie_cod
#undef mk_num_mul2_crash_cie_coe
